{% set name = "seqlogo" %}

{% set version = "5.2.9001" %}


package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e9dd8ea53999247de359af53f1331b9422dbed454f6072817230de2a2acd4e0


build:
  skip: True  # [py27]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - pandas
    - pytest
    - python
    - weblogo
    - ghostscript

test:
  imports:
    - seqlogo

about:
  home: https://github.com/betteridiot/seqlogo
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "Python port of the R Bioconductor `seqlogo` package"

extra:
  recipe-maintainers:
    - betteridiot
